import { Geist, Geist_Mono, Alfa_Slab_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header";
import Footer from "@/components/Footer";

// Next.js layout.tsx

const alpha = Alfa_Slab_One({
  subsets: ["latin"],
  weight: ["400"], // Choose weights
  variable: "--font-alpha",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${alpha.variable} antialiased`}
      >
          <Navbar/>
         <main className="space-y-20 md:space-y-28 pb-20">
          {children}
        </main>
          <Footer/>
      </body>
    </html>
  );
}
